---
  - name: Start PostgreSQL and enable at boot
    service: name=postgresql
            enabled=yes
            state=started

  - name: Restart Postgresql
    service: name=postgresql state=restarted
      